=== RevathiNimmy/pureinsurance/Navigator XM Roadmaps/navigatorxmV2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by  () -->
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by Internal Use (Sirius Financial Solutions Plc) -->
<!-- NavigatorXM Data Type Definition  -->
<!-- Revision History : RDC 02062003 Version 2.0 -->
<!-- Revision History : RFC 10062003 Changes required for conversion program. -->
<!--SET 27/01/2004:	Added optional parameters for 
	ShowWMTaskInterface - Displays an interface that allows the user to specify
	the user and/or group for the newly created task. Defaults to True.
		
	CheckSystemOption - Load the associated step based on the value of the system option. The step will
	only be loaded if the value returned matches the value specified in the 'SystemOptionValue'
	parameter. This parameter expects the numeric value of the system option to be checked.
		
	SystemOptionValue   - This option must be used in conjuntion with the CheckSystemOption.
	The associated step will only be loaded if the value returned matches the value specified in this paramter. -->
<!--PN17474 : Optional Map parameter ResetKeysOnRestart - If True, resets the current Key Array if the Map is restarted.  Defaults to True. -->
<!--DD 05/08/2005: Added additional action steps -->
<!ELEMENT MAP (STEP*)>
<!ATTLIST MAP
	WMTaskCode CDATA #REQUIRED
	WMTaskDescription CDATA #REQUIRED
	ImageURL CDATA #REQUIRED
	TransactionType CDATA #REQUIRED
	ProcessMode CDATA #REQUIRED
	AutoClose CDATA #REQUIRED
	NavigatorDriven CDATA #REQUIRED
	Core CDATA #REQUIRED
	Title CDATA #REQUIRED
	RoadmapName CDATA #REQUIRED
	Version CDATA #REQUIRED
	ElementID ID #REQUIRED
	ResetKeysOnRestart CDATA "True"
	ResourceId CDATA ""
>
<!ELEMENT SUBMAP (STEP*)>
<!ATTLIST SUBMAP
	Code CDATA #REQUIRED
	Description CDATA #REQUIRED
	ElementID ID #REQUIRED
>
<!ELEMENT STEP (SUBMAP?, KEY*)>
<!ATTLIST STEP
	Description CDATA #REQUIRED
	Component CDATA #REQUIRED
	Type CDATA #REQUIRED
	CancelAction CDATA #REQUIRED
	OKAction CDATA #REQUIRED
	OKSteps CDATA #REQUIRED
	CancelSteps CDATA #REQUIRED
	ComponentAction CDATA #REQUIRED
	ServerSide CDATA #REQUIRED
	CreateWMTask CDATA #REQUIRED
	ElementID ID #REQUIRED
	ResumeStep CDATA #REQUIRED
	Core CDATA #REQUIRED
	Submap CDATA #REQUIRED
	OKNewRoadmap CDATA #REQUIRED
	CancelNewRoadmap CDATA #REQUIRED
	ShowWMTaskInterface CDATA "True"
	CheckSystemOption CDATA ""
	SystemOptionValue CDATA ""
	CheckProductOption CDATA ""
	ProductOptionValue CDATA ""
	Action1Action CDATA ""
	Action1Steps CDATA ""
	Action2Action CDATA ""
	Action2Steps CDATA ""
	ResourceId CDATA ""
>
<!ELEMENT KEY (#PCDATA)>
<!ATTLIST KEY
	Name CDATA #REQUIRED
	Value CDATA #REQUIRED
	ElementID ID #REQUIRED
>

=== RevathiNimmy/pureinsurance/Navigator XM Roadmaps/OPENCLMNT.XML
<?xml version="1.0"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by Internal Use (Sirius Financial Solutions Plc) -->
<!-- pmnav_map_id = 18 -->
<!DOCTYPE MAP SYSTEM "navigatorxmv2.dtd">
<MAP WMTaskCode="OPENCLM" WMTaskDescription="Complete OpenClaim" ImageURL="http://www.siriusgroup.co.uk" TransactionType="C_CO" ProcessMode="0" AutoClose="False" NavigatorDriven="True" Title="NavigatorXM" RoadmapName="Open Claim (No Transactions)" Core="1" Version="200" ElementID="E1">
	<STEP Description="Find Policy" Component="iSIRFindInsurance.Interface_Renamed" Type="FF" CancelAction="AP" OKAction="F1" OKSteps="1" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E2"/>
	<STEP Description="Claim Details" Component="iOpenClaim.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E3">
		<KEY Name="claim_mode" Value="1" ElementID="E4"/>
	</STEP>
	<STEP Description="Check Unpaid Status" Component="iCLMCheckUnpaidPremium.Interface_Renamed" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E19"/>
	<STEP Description="Information Check list" Component="iCLMInfoChklst.Interface_Renamed" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E5">
		<KEY Name="DeleteWorkTableFlag" Value="1" ElementID="E6"/>
	</STEP>
	<STEP Description="Risk Details" Component="iCLMRiskDetails.Interface_Renamed" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E7">
		<KEY Name="no_transactions" Value="1" ElementID="E21"/>
	</STEP>
	<STEP Description="Coinsurance Recoveries" Component="iCLMCoinsuranceRecoveries.Interface_Renamed" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E8"/>
	<STEP Description="Reinsurance Recoveries" Component="iCLMReinsurance.Interface_Renamed" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E9"/>
	<STEP Description="Salvage Recovery" Component="iCLMRecovery.Interface_Renamed" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E10">
		<KEY Name="recovery_is_salvage" Value="1" ElementID="E17"/>
	</STEP>
	<STEP Description="Third Party Recovery" Component="iCLMRecovery.Interface_Renamed" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E11">
		<KEY Name="recovery_is_salvage" Value="0" ElementID="E18"/>
	</STEP>
	<STEP Description="Update Claim Details" Component="iCLMChangeClaimStatus.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E12">
		<KEY Name="no_transactions" Value="1" ElementID="E20"/>
	</STEP>
</MAP>

=== RevathiNimmy/pureinsurance/Navigator XM Roadmaps/PMBNB.XML
<?xml version="1.0"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by Rob Courtney (Sirius Financial Systems) -->
<!-- pmnav_map_id = 253 -->
<!DOCTYPE MAP SYSTEM "navigatorxmV2.dtd">
<MAP WMTaskCode="PMBNB" WMTaskDescription="Complete New Business" ImageURL="http://www.siriusgroup.co.uk" TransactionType="RN D" ProcessMode="4" AutoClose="False" NavigatorDriven="True" Title="NavigatorXM" RoadmapName="New Business - Stage 1" Core="1" ElementID="E1" Version="200">
	<STEP Description="Find Client" Component="iPMBFindParty.Interface_Renamed" Type="FF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E2"/>
	<STEP Description="Add Client Text Files" Component="iPMBRoadmap.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E3">
		<KEY Name="nav_step" Value="ACLTEXT" ElementID="E4"/>
	</STEP>
	<STEP Description="Select Policy Package" Component="iPMBPolicyPackage.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="False" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" CheckProductOption="75" ProductOptionValue="1" ElementID="E67"/>
	<STEP Description="Add a policy" Component="iPMBPolicy.Interface_Renamed" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E15"/>
	<STEP Description="Add risk info" Component="iPMBRisk.Interface_Renamed" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E16"/>
	<STEP Description="Add policy text files" Component="iPMBRoadmap.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E17">
		<KEY Name="nav_step" Value="APLTEXT" ElementID="E18"/>
	</STEP>
	<STEP Description="Raise debit" Component="iPMBRoadmap.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E29">
		<KEY Name="nav_step" Value="DEBIT" ElementID="E30"/>
	</STEP>
	<STEP Description="Cash List" Component="iACTCashList.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="True" Core="1" CheckSystemOption="66" SystemOptionValue="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E63"/>
	<STEP Description="Cash List Item" Component="iACTCashListItem.Interface_Renamed" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="True" CheckSystemOption="66" SystemOptionValue="1" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E64">
		<KEY Name="allow_allocate_button" Value="-1" ElementID="E65"/>
		<KEY Name="cash_list_allocation_roadmap" Value="CLIENTCASH" ElementID="E66"/>
	</STEP>
    <STEP Description="Letter to client" Component="iPMBRoadmap.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="True" CheckSystemOption="66" SystemOptionValue="1" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E42">
		<KEY Name="nav_step" Value="DOCUMENT" ElementID="E43"/>
		<KEY Name="roadmap_document" Value="NBDOC1" ElementID="E44"/>
	</STEP>
	<STEP Description="Await documents from insurer" Component="iPMBRoadmap.NavigatorV3" Type="DF" CancelAction="AP" OKAction="CP" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E45">
		<KEY Name="nav_step" Value="WMTASK" ElementID="E46"/>
		<KEY Name="wm_task" Value="PMBNB5" ElementID="E47"/>
		<KEY Name="wm_description" Value="[NB] Awaiting documents from Insurer" ElementID="E48"/>
		<KEY Name="wm_step" Value="WMNB4" ElementID="E49"/>
	</STEP>
</MAP>

=== RevathiNimmy/pureinsurance/Navigator XM Roadmaps/COMMPAY.xml
<?xml version="1.0"?>
<!DOCTYPE MAP SYSTEM "navigatorxmV2.dtd">
<MAP WMTaskCode="COMMPAY" WMTaskDescription="Commission Payments" ImageURL="http://www.siriusgroup.co.uk" TransactionType="NB" ProcessMode="0" AutoClose="True" NavigatorDriven="True" Title="NavigatorXM" RoadmapName="Commission Payments" Core="1" Version="27" ElementID="E1">
	<STEP Description="Find Agents" Component="iACTAgentSelect.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E2">
		<KEY Name="OverrideFind" Value="1" ElementID="E21"/>
		<KEY Name="FindType" Value="0" ElementID="E22"/>
		<KEY Name="CF;party_party_type_id;R;0" Value="AG" ElementID="E23"/>
		<KEY Name="DefaultFindScreen" Value="iPMBFindPartyWrapper.NavigatorV3" ElementID="E24"/>
		<KEY Name="special_party" Value="AG" ElementID="E25"/>
		<KEY Name="MultiSelection" Value="True" ElementID="E26"/>
		<KEY Name="PMWrkTaskCode" Value="COMMPAY" ElementID="E27"/>
	</STEP>
	<STEP Description="Agent Summary" Component="iACTCommissionPayments.NavigatorV3" Type="FF" CancelAction="AP" OKAction="CP" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E4">
	</STEP>
</MAP>

=== RevathiNimmy/pureinsurance/Navigator XM Roadmaps/UNDERMTANT.XML
<?xml version="1.0"?>
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by Internal Use (Sirius Financial Solutions Plc) -->
<!-- pmnav_map_id = 59 -->
<!DOCTYPE MAP SYSTEM "navigatorxmv2.dtd">
<MAP WMTaskCode="" WMTaskDescription="Underwriting MTA (No Transactions)" ImageURL="http://www.siriusgroup.co.uk" TransactionType="MTA" ProcessMode="32" AutoClose="False" NavigatorDriven="True" Title="NavigatorXM" RoadmapName="Underwriting MTA (No Transactions)" Core="1" ElementID="E1" Version="200">
	<STEP Description="Underwriting Find Party" Component="iPMBFindPartyWrapper.NavigatorV3" Type="FF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E2"/>
	<STEP Description="List Policies" Component="iPMUListPolicy.NavigatorV3" Type="FF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="True" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E3">
		<KEY Name="insurance_file_type" Value="5" ElementID="E4"/>
	</STEP>
	<STEP Description="List Policy Version" Component="iPMUListPolicyVersion.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E5"/>
	<STEP Description="Underwriting Policy" Component="iPMUPolicy.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E6"/>
	<STEP Description="Underwriting Coinsurance" Component="iPMUCoinsurance.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E7"/>
	<STEP Description="List Risks" Component="iPMUListRisks.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E8" Action1Action="BX" Action1Steps="2">
		<KEY Name="claim_mode" Value="2" ElementID="E23"/>
		<KEY Name="RoadmapDisablesInstalments" Value="true" ElementID="E43"/>
		<KEY Name="no_transactions" Value="1" ElementID="E44"/>
	</STEP>
</MAP>

=== RevathiNimmy/pureinsurance/Navigator XM Roadmaps/PAYCLM.XML
<?xml version="1.0"?>
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by Internal Use (Sirius Financial Solutions Plc) -->
<!-- pmnav_map_id = 42 -->
<!DOCTYPE MAP SYSTEM "navigatorxmv2.dtd">
<MAP WMTaskCode="PAYCLM" WMTaskDescription="Complete Payment Of Claim" ImageURL="http://www.siriusgroup.co.uk" TransactionType="C_CP" ProcessMode="0" AutoClose="False" NavigatorDriven="True" Title="NavigatorXM" RoadmapName="Payment Of Claim" Core="1" ElementID="E1" Version="200">
	<STEP Description="Find Claim" Component="iCLMFindClaim.Interface_Renamed" Type="FF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E2"/>
	<STEP Description="Claim Details" Component="iOpenClaim.NavigatorV3" Type="DF" CancelAction="FX" OKAction="F1" OKSteps="0" CancelSteps="14" ComponentAction="0" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" Action1Action="FX" Action1Steps="4" ElementID="E3"/>
	<STEP Description="Check Unpaid Status" Component="iCLMCheckUnpaidPremium.Interface_Renamed" Type="DF" CancelAction="FX" OKAction="F1" OKSteps="0" CancelSteps="13" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E4"/>
	<STEP Description="Check Deferred Reinsurance" Component="iCLMCheckDeferredRI.NavigatorV3" Type="DF" CancelAction="FX" OKAction="F1" OKSteps="0" CancelSteps="12" ComponentAction="0" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E5"/>
	<STEP Description="Information Checklist" Component="iCLMInfoChklst.Interface_Renamed" Type="DF" CancelAction="FX" OKAction="F1" OKSteps="0" CancelSteps="11" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E6">
		<KEY Name="DeleteWorkTableFlag" Value="1" ElementID="E7"/>
	</STEP>
	<STEP Description="Risk Details" Component="iCLMRiskDetails.Interface_Renamed" Type="DF" CancelAction="FX" OKAction="F1" OKSteps="0" CancelSteps="10" ComponentAction="2" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E9"/>
	<STEP Description="Coinsurance Payment" Component="iCLMCoinsuranceRecoveries.Interface_Renamed" Type="DF" CancelAction="FX" OKAction="F1" OKSteps="0" CancelSteps="9" ComponentAction="2" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E11"/>
	<STEP Description="Reinsurance Payment" Component="iCLMReinsurance.Interface_Renamed" Type="DF" CancelAction="FX" OKAction="F1" OKSteps="0" CancelSteps="8" ComponentAction="2" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E12"/>
	<STEP Description="Update Claim Details" Component="iCLMChangeClaimStatus.NavigatorV3" Type="DF" CancelAction="FX" OKAction="F1" OKSteps="0" CancelSteps="7" ComponentAction="2" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" Action1Action="FX" Action1Steps="3" ElementID="E13"/>
	<STEP Description="Cash List" Component="iACTCashList.NavigatorV3" Type="DF" CancelAction="FX" OKAction="F1" OKSteps="" CancelSteps="2" ComponentAction="1" ServerSide="False" CreateWMTask="False" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E24">
		<KEY Name="cash_list_roadmap" Value="PAYMENTS" ElementID="E25"/>
	</STEP>
	<STEP Description="Payment" Component="iACTCashListItem.Interface_Renamed" Type="DF" CancelAction="F1" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="False" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E26">
		<KEY Name="cash_list_item_mode" Value="2" ElementID="E27"/>
		<KEY Name="allow_allocate_button" Value="0" ElementID="E28"/>
	</STEP>
	<STEP Description="Check Status" Component="iCLMCloseClaim.NavigatorV3" Type="DF" CancelAction="FX" OKAction="F1" OKSteps="0" CancelSteps="4" ComponentAction="2" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E14"/>
	<STEP Description="Generate Claim Payment Documents?" Component="iPMDecision.Interface_Renamed" Type="QF" CancelAction="FX" OKAction="F1" OKSteps="0" CancelSteps="1" ComponentAction="0" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E15">
		<KEY Name="decision_title" Value="Documentation" ElementID="E16"/>
		<KEY Name="decision_text" Value="Generate Claim Payment Advice?" ElementID="E17"/>
	</STEP>
	<STEP Description="Produce Claim Payment Documents" Component="iCLMGetClaimDocuments.NavigatorV3" Type="DF" CancelAction="FX" OKAction="F1" OKSteps="0" CancelSteps="1" ComponentAction="0" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1 " Submap="" OKNewRoadmap=" " CancelNewRoadmap="" ElementID="E18"/>
	<STEP Description="Do you wish to make further payments?" Component="iPMDecision.Interface_Renamed" Type="QF" CancelAction="F1" OKAction="BX" OKSteps="9" CancelSteps="0" ComponentAction="0" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E19">
		<KEY Name="decision_title" Value="More payments" ElementID="E20"/>
		<KEY Name="decision_text" Value="Do you wish to make further payments?" ElementID="E21"/>
		<KEY Name="FurtherPayments" Value="1" ElementID="E22"/>
	</STEP>
	<STEP Description="Unlock Claim" Component="iCLMUnlock.NavigatorV3" Type="DF" CancelAction="AP" OKAction="CP" OKSteps="0" CancelSteps="0" ComponentAction="0" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E23"/>
</MAP>

=== RevathiNimmy/pureinsurance/Navigator XM Roadmaps/VCLAIM.XML
<?xml version="1.0"?>
<!-- pmnav_map_id = 61 -->
<!DOCTYPE MAP SYSTEM "navigatorxmv2.dtd">
<MAP WMTaskCode="VCLAIM" WMTaskDescription="Complete View Claim" ImageURL="http://www.siriusgroup.co.uk" TransactionType="REN" ProcessMode="0" AutoClose="False" NavigatorDriven="True" Title="NavigatorXM" RoadmapName="View Claim" Core="1" Version="200" ElementID="E1">
	<STEP Description="Find Claim" Component="iCLMFindClaim.Interface_Renamed" Type="FF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="0" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E2">
		<KEY Name="SelectVersion" Value="1" ElementID="E3"/>
	</STEP>
	<STEP Description="Claim Details" Component="iOpenClaim.NavigatorV3" Type="DF" CancelAction="BX" OKAction="F1" OKSteps="0" CancelSteps="1" ComponentAction="0" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E4">
		<KEY Name="claim_ref" Value="2" ElementID="E5"/>
	</STEP>
	<STEP Description="Information Checklist" Component="iCLMInfoChklst.Interface_Renamed" Type="DF" CancelAction="BX" OKAction="F1" OKSteps="0" CancelSteps="2" ComponentAction="0" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E6">
		<KEY Name="DeleteWorkTableFlag" Value="1" ElementID="E7"/>
	</STEP>
	<STEP Description="Risk Details" Component="iCLMRiskDetails.Interface_Renamed" Type="DF" CancelAction="BX" OKAction="F1" OKSteps="0" CancelSteps="3" ComponentAction="0" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E8">
	</STEP>
	<STEP Description="Coinsurance Recoveries" Component="iCLMCoinsuranceRecoveries.Interface_Renamed" Type="DF" CancelAction="BX" OKAction="F1" OKSteps="0" CancelSteps="4" ComponentAction="0" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E9">
	</STEP>
	<STEP Description="Reinsurance Recoveries" Component="iCLMReinsurance.Interface_Renamed" Type="DF" CancelAction="BX" OKAction="F1" OKSteps="0" CancelSteps="5" ComponentAction="0" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E10">
	</STEP>
	<STEP Description="Salvage Recovery" Component="iCLMRecovery.Interface_Renamed" Type="DF" CancelAction="BX" OKAction="F1" OKSteps="0" CancelSteps="6" ComponentAction="0" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E11">
		<KEY Name="recovery_is_salvage" Value="1" ElementID="E12"/>
	</STEP>
	<STEP Description="Third Party Recovery" Component="iCLMRecovery.Interface_Renamed" Type="DF" CancelAction="BX" OKAction="BX" OKSteps="7" CancelSteps="7" ComponentAction="0" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E13">
		<KEY Name="recovery_is_salvage" Value="0" ElementID="E14"/>
	</STEP>
</MAP>

=== RevathiNimmy/pureinsurance/Navigator XM Roadmaps/MTNCMPLT.XML
<?xml version="1.0" ?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by Steve Thomas (Sirius Financial Systems) -->
<!-- pmnav_map_id = ?? -->
<!DOCTYPE MAP SYSTEM "navigatorxmV2.dtd"[]>
<MAP WMTaskCode="OPNCMPLT" WMTaskDescription="Maintain Complaint" ImageURL="http://www.siriusgroup.co.uk" TransactionType="NB" ProcessMode="1" AutoClose="False" NavigatorDriven="True" Title="NavigatorXM" RoadmapName="Maintain Complaint" Core="1" ElementID="E1" Version="200">
	<STEP Description="Find Client" Component="iPMBFindParty.Interface_Renamed" Type="FF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="0" ServerSide="False" CreateWMTask="False" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E2"/>
	<STEP Description="Find Complaint" Component="iPMBFindComplaint.Interface_Renamed" Type="FF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="0" ServerSide="False" CreateWMTask="False" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E3"/>
	<STEP Description="Update Complaint Details" Component="iPMBComplaint.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="False" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E8" />
	<STEP Description="Print Letter?" Component="iPMDecision.Interface_Renamed" Type="QF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E9">
		<KEY Name="decision_title" Value="Print Letter?" ElementID="E10" />
		<KEY Name="decision_text" Value="Do you wish to print a letter?" ElementID="E11" />
	</STEP>
	<STEP Description="Select Document" Component="iPMBFindDocTemplate.NavigatorV3" Type="FF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="0" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E12" />
	<STEP Description="Print Document" Component="iPMBDocTemplate.NavigatorV3" Type="FF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="0" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E13">
		<KEY Name="ArchiveAfterPrinting" Value="1" ElementID="E14" />
	</STEP>
</MAP>
