=== RevathiNimmy/pureinsurance/Navigator XM Roadmaps/navigatorxmV2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by  () -->
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by Internal Use (Sirius Financial Solutions Plc) -->
<!-- NavigatorXM Data Type Definition  -->
<!-- Revision History : RDC 02062003 Version 2.0 -->
<!-- Revision History : RFC 10062003 Changes required for conversion program. -->
<!--SET 27/01/2004:	Added optional parameters for 
	ShowWMTaskInterface - Displays an interface that allows the user to specify
	the user and/or group for the newly created task. Defaults to True.
		
	CheckSystemOption - Load the associated step based on the value of the system option. The step will
	only be loaded if the value returned matches the value specified in the 'SystemOptionValue'
	parameter. This parameter expects the numeric value of the system option to be checked.
		
	SystemOptionValue   - This option must be used in conjuntion with the CheckSystemOption.
	The associated step will only be loaded if the value returned matches the value specified in this paramter. -->
<!--PN17474 : Optional Map parameter ResetKeysOnRestart - If True, resets the current Key Array if the Map is restarted.  Defaults to True. -->
<!--DD 05/08/2005: Added additional action steps -->
<!ELEMENT MAP (STEP*)>
<!ATTLIST MAP
	WMTaskCode CDATA #REQUIRED
	WMTaskDescription CDATA #REQUIRED
	ImageURL CDATA #REQUIRED
	TransactionType CDATA #REQUIRED
	ProcessMode CDATA #REQUIRED
	AutoClose CDATA #REQUIRED
	NavigatorDriven CDATA #REQUIRED
	Core CDATA #REQUIRED
	Title CDATA #REQUIRED
	RoadmapName CDATA #REQUIRED
	Version CDATA #REQUIRED
	ElementID ID #REQUIRED
	ResetKeysOnRestart CDATA "True"
	ResourceId CDATA ""
>
<!ELEMENT SUBMAP (STEP*)>
<!ATTLIST SUBMAP
	Code CDATA #REQUIRED
	Description CDATA #REQUIRED
	ElementID ID #REQUIRED
>
<!ELEMENT STEP (SUBMAP?, KEY*)>
<!ATTLIST STEP
	Description CDATA #REQUIRED
	Component CDATA #REQUIRED
	Type CDATA #REQUIRED
	CancelAction CDATA #REQUIRED
	OKAction CDATA #REQUIRED
	OKSteps CDATA #REQUIRED
	CancelSteps CDATA #REQUIRED
	ComponentAction CDATA #REQUIRED
	ServerSide CDATA #REQUIRED
	CreateWMTask CDATA #REQUIRED
	ElementID ID #REQUIRED
	ResumeStep CDATA #REQUIRED
	Core CDATA #REQUIRED
	Submap CDATA #REQUIRED
	OKNewRoadmap CDATA #REQUIRED
	CancelNewRoadmap CDATA #REQUIRED
	ShowWMTaskInterface CDATA "True"
	CheckSystemOption CDATA ""
	SystemOptionValue CDATA ""
	CheckProductOption CDATA ""
	ProductOptionValue CDATA ""
	Action1Action CDATA ""
	Action1Steps CDATA ""
	Action2Action CDATA ""
	Action2Steps CDATA ""
	ResourceId CDATA ""
>
<!ELEMENT KEY (#PCDATA)>
<!ATTLIST KEY
	Name CDATA #REQUIRED
	Value CDATA #REQUIRED
	ElementID ID #REQUIRED
>

=== RevathiNimmy/pureinsurance/Navigator XM Roadmaps/UNDERNB.XML
<?xml version="1.0"?>  <!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by Internal Use (Sirius Financial Solutions Plc) -->  <!-- pmnav_map_id = 54 -->  <!DOCTYPE MAP SYSTEM "navigatorxmv2.dtd">  <MAP WMTaskCode="UNDERNB" WMTaskDescription="Complete Underwriting New Business" ImageURL="http://www.siriusgroup.co.uk" TransactionType="NB" ProcessMode="2" AutoClose="False" NavigatorDriven="True" Title="NavigatorXM" RoadmapName="Underwriting New Business" Core="1" ElementID="E1" Version="200">   <STEP Description="Underwriting Find Party" Component="iPMBFindPartyWrapper.NavigatorV3" Type="FF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E2"/>   <STEP Description="List Policies" Component="iPMUListPolicy.NavigatorV3" Type="FF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E3">    <KEY Name="insurance_file_type" Value="4" ElementID="E4"/>   </STEP>   <STEP Description="Find Product Type" Component="iPMUFindProductType.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E7"/>   <STEP Description="Underwriting Policy" Component="iPMUPolicy.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E10"/>   <STEP Description="Underwriting Coinsurance" Component="iPMUCoinsurance.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E11"/>   <STEP Description="List Risks" Component="iPMUListRisks.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" Action1Action="BX" Action1Steps="2" Action2Action="QS" Action2Steps="0" ElementID="E12">    <KEY Name="TaskGroupCode" Value="New Business" ElementID="E43"/>    <KEY Name="claim_mode" Value="2" ElementID="E37"/>   </STEP>   <STEP Description="Statistics" Component="iPMUStats.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E38"/>   <STEP Description="Plan Maintenance" Component="iPMBFinancePlanMaint.NavigatorV3" Type="DF" CancelAction="F1" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E44">    <KEY Name="TaskGroupCode" Value="New Business" ElementID="E45"/>   </STEP>   <STEP Description="Accumulation Values" Component="iPMUAccumulationValues.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E46"/>   <STEP Description="Produce Schedule" Component="iPMUGetDocument.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E47" ResourceId="100">    <KEY Name="document_id" Value="4" ElementID="E48"/>    <KEY Name="short_code" Value="schedule" ElementID="E49"/>   </STEP>   <STEP Description="Produce Certificate" Component="iPMUGetDocument.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E50">    <KEY Name="document_id" Value="5" ElementID="E51"/>    <KEY Name="short_code" Value="certificate" ElementID="E52"/>   </STEP>   <STEP Description="Produce Debit Note" Component="iPMUGetDocument.NavigatorV3" Type="DF" CancelAction="AP" OKAction="CP" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E53" ResourceId="101">    <KEY Name="document_id" Value="3" ElementID="E54"/>    <KEY Name="short_code" Value="debitnote" ElementID="E55"/>   </STEP>  </MAP>

=== RevathiNimmy/pureinsurance/Navigator XM Roadmaps/UNDERMTA.XML
<?xml version="1.0"?>  <!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by Internal Use (Sirius Financial Solutions Plc) -->  <!-- pmnav_map_id = 58 -->  <!DOCTYPE MAP SYSTEM "navigatorxmv2.dtd">  <MAP WMTaskCode="UnderMTA" WMTaskDescription="Complete Underwriting MTA" ImageURL="http://www.siriusgroup.co.uk" TransactionType="MTA" ProcessMode="32" AutoClose="False" NavigatorDriven="True" Title="NavigatorXM" RoadmapName="Underwriting MTA" Core="1" ElementID="E1" Version="200">   <STEP Description="Underwriting Find Party" Component="iPMBFindPartyWrapper.NavigatorV3" Type="FF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E2"/>   <STEP Description="List Policies" Component="iPMUListPolicy.NavigatorV3" Type="FF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="True" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E3">    <KEY Name="insurance_file_type" Value="5" ElementID="E4"/>   </STEP>   <STEP Description="List Policy Version" Component="iPMUListPolicyVersion.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E5"/>   <STEP Description="Underwriting Policy" Component="iPMUPolicy.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E8"/>   <STEP Description="Underwriting Coinsurance" Component="iPMUCoinsurance.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E9"/>   <STEP Description="List Risks" Component="iPMUListRisks.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E10" Action1Action="BX" Action1Steps="2">    <KEY Name="claim_mode" Value="2" ElementID="E35"/>    <KEY Name="TaskGroupCode" Value="MTA" ElementID="E60"/>   </STEP>   <STEP Description="Statistics" Component="iPMUStats.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E36"/>   <STEP Description="Plan Maintenance" Component="iPMBFinancePlanMaint.NavigatorV3" Type="DF" CancelAction="F1" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E42">    <KEY Name="TaskGroupCode" Value="MTA" ElementID="E43"/>   </STEP>   <STEP Description="Accumulation Values" Component="iPMUAccumulationValues.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E44"/>   <STEP Description="Produce Schedule" Component="iPMUGetDocument.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E45" ResourceId="102">    <KEY Name="document_id" Value="4" ElementID="E46"/>    <KEY Name="short_code" Value="schedule" ElementID="E47"/>   </STEP>   <STEP Description="Produce Certificate" Component="iPMUGetDocument.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E48">    <KEY Name="document_id" Value="5" ElementID="E49"/>    <KEY Name="short_code" Value="certificate" ElementID="E50"/>   </STEP>   <STEP Description="Produce Debit Note" Component="iPMUGetDocument.NavigatorV3" Type="DF" CancelAction="AP" OKAction="CP" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E51" ResourceId="101">    <KEY Name="document_id" Value="3" ElementID="E52"/>    <KEY Name="short_code" Value="debitnote" ElementID="E53"/>   </STEP>  </MAP>

=== RevathiNimmy/pureinsurance/Navigator XM Roadmaps/UNDERNBNT.XML
<?xml version="1.0"?>
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by Internal Use (Sirius Financial Solutions Plc) -->
<!-- pmnav_map_id = 54 -->
<!DOCTYPE MAP SYSTEM "navigatorxmv2.dtd">
<MAP WMTaskCode="UNDNBNT" WMTaskDescription="Underwriting New Business (No Transactions)" ImageURL="http://www.siriusgroup.co.uk" TransactionType="NB" ProcessMode="2" AutoClose="False" NavigatorDriven="True" Title="NavigatorXM" RoadmapName="Underwriting New Business (No Transactions)" Core="1" ElementID="E1" Version="200">
	<STEP Description="Underwriting Find Party" Component="iPMBFindPartyWrapper.NavigatorV3" Type="FF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E2"/>
	<STEP Description="List Policies" Component="iPMUListPolicy.NavigatorV3" Type="FF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E3">
		<KEY Name="insurance_file_type" Value="4" ElementID="E4"/>
	</STEP>
	<STEP Description="Find Product Type" Component="iPMUFindProductType.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E7"/>
	<STEP Description="Underwriting Policy" Component="iPMUPolicy.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E10"/>
	<STEP Description="Underwriting Coinsurance" Component="iPMUCoinsurance.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E11"/>
	<STEP Description="List Risks" Component="iPMUListRisks.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E12" Action1Action="BX" Action1Steps="2">
		<KEY Name="TaskGroupCode" Value="New Business" ElementID="E45"/>
		<KEY Name="claim_mode" Value="2" ElementID="E23"/>
		<KEY Name="RoadmapDisablesInstalments" Value="true" ElementID="E43"/>
		<KEY Name="no_transactions" Value="1" ElementID="E44"/>
	</STEP>
</MAP>

=== RevathiNimmy/pureinsurance/Navigator XM Roadmaps/PMBADJ1.XML
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by Rob Courtney (Sirius Financial Systems) -->
<!-- pmnav_map_id = 260 -->
<!DOCTYPE MAP SYSTEM "navigatorxmV2.dtd">
<MAP WMTaskCode="PMBADJ1" WMTaskDescription="Complete Adjustments" ImageURL="http://www.siriusgroup.co.uk" TransactionType="G_MTA" ProcessMode="64" AutoClose="False" NavigatorDriven="True" Title="NavigatorXM" RoadmapName="Adjustments - Stage 1" Core="1" Version="200" ElementID="E1">
    <STEP Description="Find Client" Component="iPMBFindParty.Interface_Renamed" Type="FF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="0" ServerSide="False" CreateWMTask="False" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E2"/>
    <STEP Description="Select Policy" Component="iPMBListPolicy.Interface_Renamed" Type="FF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="0" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E3">
            <KEY Name="nav_process_code" Value="PMBADJ1" ElementID="E20"/>
    </STEP>
    <STEP Description="Update Policy Details" Component="iPMBPolicy.Interface_Renamed" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E4"/>
    <STEP Description="Update Risk Information" Component="iPMBRisk.Interface_Renamed" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E5"/>
    <STEP Description="Update Policy Text Files" Component="iPMBRoadmap.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E6">
        <KEY Name="nav_step" Value="UPLTEXT" ElementID="E7"/>
    </STEP>
    <STEP Description="Letter To Client With Schedule" Component="iPMBRoadmap.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E8">
        <KEY Name="nav_step" Value="DOCUMENT" ElementID="E9"/>
        <KEY Name="roadmap_document" Value="ADJDOC1" ElementID="E10"/>
    </STEP>
    <STEP Description="Select Debit Or Credit" Component="iPMTransactionType.Interface_Renamed" Type="QF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="0" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E11"/>
    <STEP Description="Raise Transaction" Component="iPMBTransactionsWrapper.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E12"/>
    <STEP Description="Cash List" Component="iACTCashList.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="True" CheckSystemOption="123" SystemOptionValue="1" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E13"/>
 
    <STEP Description="Cash List Item" Component="iACTCashListItem.Interface_Renamed" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="True" CheckSystemOption="123" SystemOptionValue="1" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E14">
        <KEY Name="allow_allocate_button" Value="-1" ElementID="E15"/>
        <KEY Name="cash_list_allocation_roadmap" Value="CLIENTCASH" ElementID="E16"/>
    </STEP>
    <STEP Description="Letter To Client With Schedule" Component="iPMBRoadmap.NavigatorV3" Type="DF" CancelAction="AP" OKAction="CP" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E17">
        <KEY Name="nav_step" Value="DOCUMENT" ElementID="E18"/>
        <KEY Name="roadmap_document" Value="ADJDOC2" ElementID="E19"/>
    </STEP>
</MAP>

=== RevathiNimmy/pureinsurance/Navigator XM Roadmaps/WMPMBMTA.XML
<!-- <?xml version="1.0"?-->
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by Steve Thomas (Sirius Financial Systems) -->
<!-- pmnav_map_id = ?? -->
<!DOCTYPE MAP SYSTEM "navigatorxmV2.dtd">
<MAP WMTaskCode="WMPMBMTA" WMTaskDescription="Generic MTA" ImageURL="http://www.siriusgroup.co.uk" TransactionType="G_MTA" ProcessMode="32" AutoClose="False" NavigatorDriven="True" Title="NavigatorXM" RoadmapName="Generic MTA" Core="1" ElementID="E1" Version="200">
	<STEP Description="Find Party" Component="iPMBFindParty.Interface_Renamed" Type="FF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="0" ServerSide="False" CreateWMTask="False" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E2">
	</STEP>
	<STEP Description="Find Policy" Component="iCNListPolicyWrapper.NavigatorV3" Type="FF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="False" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E3">
		<KEY Name="insurance_file_type" Value="POLICY" ElementID="E4"/>
	</STEP>
	<STEP Description="Find Policy Version" Component="iPMUListPolicyVersion.Interface_Renamed" Type="FF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="False" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E5">
	</STEP>
	<STEP Description="Retrieve Quote Control" Component="iPMBMTATypeControl.Interface_Renamed" Type="DF" CancelAction="FX" OKAction="F1" OKSteps="0" CancelSteps="3" ComponentAction="2" ServerSide="False" CreateWMTask="False" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E6">
	</STEP>
	<STEP Description="Choose MTA Type" Component="iPMBMTAChoice.Interface_Renamed" Type="DF" CancelAction="BX" OKAction="F1" OKSteps="0" CancelSteps="2" ComponentAction="2" ServerSide="False" CreateWMTask="False" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E7">
	</STEP>
	<STEP Description="Edit Risk Data" Component="iPMURisk.Interface_Renamed" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="False" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E8">
	</STEP>
	<STEP Description="Quote Display" Component="iPMBQuoteDisplay.Interface_Renamed" Type="DF" CancelAction="B1" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="0" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E9">
		<KEY Name="process_type" Value="MTA_Q" ElementID="E10"/>
		<KEY Name="wm_task" Value="WMPMBMTA" ElementID="E44"/>
	</STEP>
	<STEP Description="Update Quote Policy" Component="bSIRQuotePolicy.NavigatorV3" Type="BO" CancelAction="AP" OKAction="F1" OKSteps="1" CancelSteps="0" ComponentAction="2" ServerSide="True" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E11">
		<KEY Name="return_status" Value="20" ElementID="E12"/>
	</STEP>
	<!-- optionally display the edit policy screen... -->
	<STEP Description="Edit Policy" Component="iPMBPolicy.Interface_Renamed" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="1" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" CheckSystemOption="202" SystemOptionValue="1" ElementID="E24">
		<KEY Name="branch_selection_not_required" Value="1" ElementID="E25"/>
	</STEP>
	<!-- ...or show payment method screen -->
	<STEP Description="Payment Method" Component="iPMBPaymentScreen.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="1" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" CheckSystemOption="202" SystemOptionValue="0" ElementID="E26"/>
	<!-- raise a debit only if the system option allows -->
	<!-- ...using the schemes component -->
	<STEP Description="Raise Debit" Component="iCNCTransactionsWrapper.NavigatorV3" Type="BO" CancelAction="AP" OKAction="F1" OKSteps="1" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" CheckSystemOption="201" SystemOptionValue="1" ElementID="E27"/>
	<!-- ... or using the standard back-office component -->
	<STEP Description="Raise Debit" Component="iPMBTransactionsWrapper.NavigatorV3" Type="DF" CancelAction="F1" OKAction="F1" OKSteps="1" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" CheckSystemOption="201" SystemOptionValue="2" ElementID="E28"/>
	<STEP Description="Cash List" Component="iACTCashList.NavigatorV3" Type="DF" CancelAction="FX" OKAction="F1" OKSteps="0" CancelSteps="2" ComponentAction="1" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" CheckSystemOption="124" SystemOptionValue="1" ShowWMTaskInterface="False" ElementID="E40">
		<KEY Name="cash_list_roadmap" Value="DECIDE" ElementID="E41"/>
	</STEP>
	<STEP Description="Cash List Item" Component="iACTCashListItem.Interface_Renamed" Type="DF" CancelAction="FX" OKAction="F1" OKSteps="0" CancelSteps="1" ComponentAction="2" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" CheckSystemOption="124" SystemOptionValue="1" ShowWMTaskInterface="False" ElementID="E42">
		<KEY Name="allow_allocate_button" Value="-1" ElementID="E43"/>
	</STEP>
	<!-- select instalment plan only if the system option allows - NOT SUPPORTED AT THE MOMENT -->
	<STEP Description="Do you wish to print the documentation?" Component="iPMDecision.Interface_Renamed" Type="QF" CancelAction="AP" OKAction="F1" OKSteps="1" CancelSteps="0" ComponentAction="0" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E17">
		<KEY Name="decision_title" Value="Letter" ElementID="E18"/>
		<KEY Name="decision_text" Value="Do you wish to produce a letter now?" ElementID="E19"/>
		<KEY Name="PMKeyNameRunMode" Value="ACMergeMode" ElementID="E20"/>
	</STEP>
	<STEP Description="Produce Letter" Component="iPMBDocProductionWrapper.NavigatorV3" Type="PO" CancelAction="AP" OKAction="F1" OKSteps="1" CancelSteps="0" ComponentAction="0" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E21">
		<KEY Name="nav_step" Value="DOCUMENT" ElementID="E22"/>
		<KEY Name="process_type" Value="MTA" ElementID="E23"/>
	</STEP>
</MAP>

=== RevathiNimmy/pureinsurance/Navigator XM Roadmaps/OpenComplaint.XML
<?xml version="1.0"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by Steve Thomas (Sirius Financial Systems) -->
<!-- pmnav_map_id = ?? -->
<!DOCTYPE MAP SYSTEM "navigatorxmV2.dtd">
<MAP WMTaskCode="OPNCMPLT" WMTaskDescription="New Complaint" ImageURL="http://www.siriusgroup.co.uk" TransactionType="NB" ProcessMode="1" AutoClose="False" NavigatorDriven="True" Title="NavigatorXM" RoadmapName="New Complaint" Core="1" ElementID="E1" Version="200">
    <STEP Description="Find Client" Component="iPMBFindParty.Interface_Renamed" Type="FF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="0" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ShowWMTaskInterface="False" ElementID="E2">
        <KEY Name="include_complaints" Value="1" ElementID="E15"/>
    </STEP>
    <STEP Description="Select Complaint Type" Component="iPMBComplaintTypeSelect.Interface_Renamed" Type="QF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="0" ServerSide="False" CreateWMTask="False" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ShowWMTaskInterface="False" ElementID="E3"/>
    <STEP Description="Add Complaint Details" Component="iPMBComplaint.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ShowWMTaskInterface="False" ElementID="E8"/>
    <STEP Description="Generate Letter?" Component="iPMDecision.Interface_Renamed" Type="QF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ShowWMTaskInterface="True" ElementID="E9">
        <KEY Name="decision_title" Value="Generate Letter?" ElementID="E10"/>
        <KEY Name="decision_text" Value="Do you wish to Generate a letter?" ElementID="E11"/>
    </STEP>
    <STEP Description="Select Letter" Component="iPMBFindDocTemplate.NavigatorV3" Type="FF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="0" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ShowWMTaskInterface="False" ElementID="E12">
        <KEY Name="doc_template_mode" Value="1" ElementID="E16"/>
    </STEP>    
    <STEP Description="Generate Letter" Component="iPMBDocTemplate.NavigatorV3" Type="FF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="0" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ShowWMTaskInterface="False" ElementID="E13" >
        <KEY Name="ArchiveAfterPrinting" Value="1" ElementID="E14" />
    </STEP>
</MAP>
