=== RevathiNimmy/pureinsurance/Navigator XM Roadmaps/navigatorxmV2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by  () -->
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by Internal Use (Sirius Financial Solutions Plc) -->
<!-- NavigatorXM Data Type Definition  -->
<!-- Revision History : RDC 02062003 Version 2.0 -->
<!-- Revision History : RFC 10062003 Changes required for conversion program. -->
<!--SET 27/01/2004:	Added optional parameters for 
	ShowWMTaskInterface - Displays an interface that allows the user to specify
	the user and/or group for the newly created task. Defaults to True.
		
	CheckSystemOption - Load the associated step based on the value of the system option. The step will
	only be loaded if the value returned matches the value specified in the 'SystemOptionValue'
	parameter. This parameter expects the numeric value of the system option to be checked.
		
	SystemOptionValue   - This option must be used in conjuntion with the CheckSystemOption.
	The associated step will only be loaded if the value returned matches the value specified in this paramter. -->
<!--PN17474 : Optional Map parameter ResetKeysOnRestart - If True, resets the current Key Array if the Map is restarted.  Defaults to True. -->
<!--DD 05/08/2005: Added additional action steps -->
<!ELEMENT MAP (STEP*)>
<!ATTLIST MAP
	WMTaskCode CDATA #REQUIRED
	WMTaskDescription CDATA #REQUIRED
	ImageURL CDATA #REQUIRED
	TransactionType CDATA #REQUIRED
	ProcessMode CDATA #REQUIRED
	AutoClose CDATA #REQUIRED
	NavigatorDriven CDATA #REQUIRED
	Core CDATA #REQUIRED
	Title CDATA #REQUIRED
	RoadmapName CDATA #REQUIRED
	Version CDATA #REQUIRED
	ElementID ID #REQUIRED
	ResetKeysOnRestart CDATA "True"
	ResourceId CDATA ""
>
<!ELEMENT SUBMAP (STEP*)>
<!ATTLIST SUBMAP
	Code CDATA #REQUIRED
	Description CDATA #REQUIRED
	ElementID ID #REQUIRED
>
<!ELEMENT STEP (SUBMAP?, KEY*)>
<!ATTLIST STEP
	Description CDATA #REQUIRED
	Component CDATA #REQUIRED
	Type CDATA #REQUIRED
	CancelAction CDATA #REQUIRED
	OKAction CDATA #REQUIRED
	OKSteps CDATA #REQUIRED
	CancelSteps CDATA #REQUIRED
	ComponentAction CDATA #REQUIRED
	ServerSide CDATA #REQUIRED
	CreateWMTask CDATA #REQUIRED
	ElementID ID #REQUIRED
	ResumeStep CDATA #REQUIRED
	Core CDATA #REQUIRED
	Submap CDATA #REQUIRED
	OKNewRoadmap CDATA #REQUIRED
	CancelNewRoadmap CDATA #REQUIRED
	ShowWMTaskInterface CDATA "True"
	CheckSystemOption CDATA ""
	SystemOptionValue CDATA ""
	CheckProductOption CDATA ""
	ProductOptionValue CDATA ""
	Action1Action CDATA ""
	Action1Steps CDATA ""
	Action2Action CDATA ""
	Action2Steps CDATA ""
	ResourceId CDATA ""
>
<!ELEMENT KEY (#PCDATA)>
<!ATTLIST KEY
	Name CDATA #REQUIRED
	Value CDATA #REQUIRED
	ElementID ID #REQUIRED
>

=== RevathiNimmy/pureinsurance/Navigator XM Roadmaps/OPNCMPLT.XML
<?xml version="1.0"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by Steve Thomas (Sirius Financial Systems) -->
<!-- pmnav_map_id = ?? -->
<!DOCTYPE MAP SYSTEM "navigatorxmV2.dtd">
<MAP WMTaskCode="OPNCMPLT" WMTaskDescription="New Complaint" ImageURL="http://www.siriusgroup.co.uk" TransactionType="NB" ProcessMode="1" AutoClose="False" NavigatorDriven="True" Title="NavigatorXM" RoadmapName="New Complaint" Core="1" ElementID="E1" Version="200">
	<STEP Description="Policy or Claim Complaint?" Component="iPMDecision.Interface_Renamed" Type="QF" CancelAction="FX" OKAction="F1" OKSteps="0" CancelSteps="3" ComponentAction="0" ServerSide="False" CreateWMTask="False" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E3">
		<KEY Name="decision_title" Value="Policy or Claim Complaint?" ElementID="E4"/>
		<KEY Name="decision_text" Value="Does this complaint relate to a Policy?" ElementID="E5"/> 
	</STEP>
	<STEP Description="Find Client" Component="iPMBFindParty.Interface_Renamed" Type="FF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="0" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E2"/>
	<STEP Description="Find Policy" Component="iPMUListPolicy.NavigatorV3" Type="FF" CancelAction="AP" OKAction="FX" OKSteps="2" CancelSteps="0" ComponentAction="0" ServerSide="False" CreateWMTask="False" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E7"/>
	<STEP Description="Find Claim" Component="iCLMFindClaim.NavigatorV3" Type="FF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="0" ServerSide="False" CreateWMTask="False" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E6"/>
	<STEP Description="Add Complaint Details" Component="iPMBComplaint.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E8"/>
	<STEP Description="Print Letter?" Component="iPMDecision.Interface_Renamed" Type="QF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E9">
		<KEY Name="decision_title" Value="Print Letter?" ElementID="E10"/>
		<KEY Name="decision_text" Value="Do you wish to print a letter?" ElementID="E11"/>
	</STEP>
	<STEP Description="Select Document" Component="iPMBFindDocTemplate.NavigatorV3" Type="FF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="0" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E12"/>
	<STEP Description="Print Document" Component="iPMBDocTemplate.NavigatorV3" Type="FF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="0" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E13" >
		<KEY Name="ArchiveAfterPrinting" Value="1" ElementID="E14" />
	</STEP>
</MAP>

=== RevathiNimmy/pureinsurance/Navigator XM Roadmaps/TPRECOVER.XML
<?xml version="1.0"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by Internal Use (Sirius Financial Solutions Plc) -->
<!-- pmnav_map_id = 40 -->
<!DOCTYPE MAP SYSTEM "navigatorxmV2.dtd">
<MAP WMTaskCode="TPRECOVER" WMTaskDescription="Complete Third Party Receipt" ImageURL="http://www.siriusgroup.co.uk" TransactionType="C_RV" ProcessMode="0" AutoClose="False" NavigatorDriven="True" Title="NavigatorXM" RoadmapName="Third Party Receipt" Core="1" Version="200" ElementID="E1">
	<STEP Description="Find Claim" Component="iCLMFindClaim.Interface_Renamed" Type="FF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E2"/>
	<STEP Description="Claim Details" Component="iOpenClaim.NavigatorV3" Type="DF" CancelAction="FX" OKAction="F1" OKSteps="0" CancelSteps="7" ComponentAction="0" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E3"/>
	<!--Start-(Arul Stephen)-(Issue No-PNREF86367)-->
	<STEP Description="Third Party Receipt" Component="iCLMRecovery.Interface_Renamed" Type="DF" CancelAction="FX" OKAction="F1" OKSteps="0" CancelSteps="6" ComponentAction="2" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E4">
		<KEY Name="recovery_is_salvage" Value="0" ElementID="E5"/>
	</STEP>
	<!--Arul Stephen-->
	<STEP Description="Coinsurance Receipt" Component="iCLMCoinsuranceRecoveries.Interface_Renamed" Type="DF" CancelAction="FX" OKAction="F1" OKSteps="0" CancelSteps="5" ComponentAction="2" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E6"/>
	<STEP Description="Reinsurance Receipt" Component="iCLMReinsurance.Interface_Renamed" Type="DF" CancelAction="FX" OKAction="F1" OKSteps="0" CancelSteps="4" ComponentAction="2" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E7"/>
	<STEP Description="Update Claim Details" Component="iCLMChangeClaimStatus.NavigatorV3" Type="DF" CancelAction="F1" OKAction="F1" OKSteps="0" CancelSteps="3" ComponentAction="2" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E8"/>
	<STEP Description="Check Status" Component="iCLMCloseClaim.NavigatorV3" Type="DF" CancelAction="FX" OKAction="F1" OKSteps="0" CancelSteps="4" ComponentAction="2" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E9"/>
	<STEP Description="Do you wish to make further Receipts?" Component="iPMDecision.Interface_Renamed" Type="QF" CancelAction="F1" OKAction="BX" OKSteps="5" CancelSteps="0" ComponentAction="0" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E10">
		<KEY Name="decision_title" Value="More Receipts" ElementID="E11"/>
		<KEY Name="decision_text" Value="Do you wish to make further Receipts?" ElementID="E12"/>
		<KEY Name="FurtherReceipts" Value="1" ElementID="E13"/>
	</STEP>
	<STEP Description="Unlock Claim" Component="iCLMUnlock.NavigatorV3" Type="DF" CancelAction="AP" OKAction="CP" OKSteps="0" CancelSteps="0" ComponentAction="0" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E14"/>
	<!--Arul Stephen-->
	<!--End-(Arul Stephen)-(Issue No-PNREF86367)-->
</MAP>

=== RevathiNimmy/pureinsurance/Navigator XM Roadmaps/MCLAIM.XML
<?xml version="1.0" encoding="UTF-8"?>
<!-- pmnav_map_id = 41 -->
<!DOCTYPE MAP SYSTEM "navigatorxmv2.dtd">
<MAP WMTaskCode="MAINCLM" WMTaskDescription="Maintain Claim" ImageURL="http://www.siriusgroup.co.uk" TransactionType="G_NB" ProcessMode="4" AutoClose="False" NavigatorDriven="False" Title="NavigatorXM" RoadmapName="Maintain Claim" Core="1" Version="200" ElementID="E1">
	<STEP Description="Find Claim" Component="iCLMFindClaim.Interface_Renamed" Type="FF" CancelAction="BX" OKAction="FX" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E2"/>
	<STEP Description="Claim Details" Component="iOpenClaim.Interface_Renamed" Type="DF" CancelAction="BX" OKAction="FX" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" CheckSystemOption="2032" SystemOptionValue="1" ElementID="E3"/>
	<STEP Description="Edit Claim Text Files" Component="iPMBTextFiles.Interface_Renamed" Type="DF" CancelAction="BX" OKAction="FX" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" CheckSystemOption="2033" SystemOptionValue="1" ElementID="E4"/>
	<STEP Description="Risk Details" Component="iCLMRiskDetails.Interface_Renamed" Type="DF" CancelAction="BX" OKAction="FX" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" CheckSystemOption="2034" SystemOptionValue="1" ElementID="E5"/>
	<STEP Description="Information Checklist" Component="iCLMInfoChklst.Interface_Renamed" Type="DF" CancelAction="BX" OKAction="FX" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" CheckSystemOption="2035" SystemOptionValue="1" ElementID="E6"/>
	<STEP Description="Third Party Recovery" Component="iCLMThirdPartyRecovery.Interface_Renamed" Type="DF" CancelAction="BX" OKAction="FX" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" CheckSystemOption="2036" SystemOptionValue="1" ElementID="E7"/>
	<STEP Description="Salvage Recovery" Component="iCLMSalvageRecovery.Interface_Renamed" Type="DF" CancelAction="BX" OKAction="FX" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" CheckSystemOption="2037" SystemOptionValue="1" ElementID="E10"/>
	<STEP Description="Claim Letter" Component="iCLMGetClaimLetter.Interface_Renamed" Type="DF" CancelAction="BX" OKAction="FX" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" CheckSystemOption="2038" SystemOptionValue="1" ElementID="E8"/>
	<STEP Description="Claim Diary" Component="iCLMCreateClaimDiary.Interface_Renamed" Type="DF" CancelAction="BX" OKAction="FX" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" CheckSystemOption="2039" SystemOptionValue="1" ElementID="E9"/>
</MAP>

=== RevathiNimmy/pureinsurance/Navigator XM Roadmaps/UWCancel.XML
<?xml version="1.0"?>
<!-- pmnav_map_id = 29 -->
<!DOCTYPE MAP SYSTEM "navigatorxmV2.dtd">
<MAP WMTaskCode="UWCancel" WMTaskDescription="Complete Underwriting Cancel Policy" ImageURL="http://www.siriusgroup.co.uk" TransactionType="MTC" 

ProcessMode="32" AutoClose="False" NavigatorDriven="True" Title="NavigatorXM" RoadmapName="Underwriting Cancel Policy" Core="1" ElementID="E1" Version="200">
	<STEP Description="Underwriting Find Party" Component="iPMBFindPartyWrapper.NavigatorV3" Type="FF" CancelAction="AP" OKAction="F1" OKSteps="0" 

CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="" Submap="" OKNewRoadmap="" CancelNewRoadmap="" 

ElementID="E2">
	</STEP>
	<STEP Description="List Policies" Component="iPMUListPolicy.NavigatorV3" Type="FF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" 

ComponentAction="1" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E3">
		<KEY Name="insurance_file_type" Value="5" ElementID="E4"/>
	</STEP>
	<STEP Description="List Policy Version" Component="iPMUListPolicyVersion.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" 

CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="" Submap="" OKNewRoadmap="" CancelNewRoadmap="" 

ElementID="E5">
	</STEP>
	<STEP Description="Policy Details" Component="" Type="" CancelAction="" OKAction="" OKSteps="" CancelSteps="" ComponentAction="" ServerSide="False" 

CreateWMTask="True" Core="1" ResumeStep="" Submap="UNDERPOLCA" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E6">
		<SUBMAP Code="UNDERPOLCA" Description="Underwriting Cancel Policy Details" ElementID="E7">
			<!-- pmnav_map_id = 30 -->
			<STEP Description="Underwriting Policy" Component="iPMUPolicy.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" 

CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="" Submap="" OKNewRoadmap="" CancelNewRoadmap="" 

ElementID="E8">
			</STEP>
			<STEP Description="Underwriting Coinsurance" Component="iPMUCoinsurance.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" 

OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="" Submap="" OKNewRoadmap="" CancelNewRoadmap="" 

ElementID="E9">
			</STEP>
			<STEP Description="List Risks" Component="iPMUListRisks.NavigatorV3" Type="DF" CancelAction="BX" OKAction="F1" OKSteps="0" 

CancelSteps="2" ComponentAction="2" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="" Submap="" OKNewRoadmap="" CancelNewRoadmap="" 

ElementID="E10" Action1Action="BX" Action1Steps="2">
			</STEP>
			<STEP Description="Statistics" Component="iPMUStats.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" 

CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="" Submap="" OKNewRoadmap="" CancelNewRoadmap="" 

ElementID="E19">
			</STEP>
      <STEP Description="Plan Maintenance" Component="iPMBFinancePlanMaint.NavigatorV3" Type="DF" CancelAction="F1" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E26">
        <KEY Name="TaskGroupCode" Value="MTC" ElementID="E27"/>
      </STEP>

      <STEP Description="Accumulation Values" Component="iPMUAccumulationValues.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" 

OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="" Submap="" OKNewRoadmap="" CancelNewRoadmap="" 

ElementID="E20">
			</STEP>
			<STEP Description="Produce Cancellation Notice" Component="iPMUGetDocument.NavigatorV3" Type="DF" CancelAction="AP" OKAction="CP" 

OKSteps="0" CancelSteps="0" ComponentAction="0" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="" Submap="" OKNewRoadmap="" CancelNewRoadmap="" 

ElementID="E24">
				<KEY Name="document_id" Value="10" ElementID="E25"/>
			</STEP>
		</SUBMAP>
	</STEP>
</MAP>

=== RevathiNimmy/pureinsurance/Navigator XM Roadmaps/OPENCLM.XML
<?xml version="1.0"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by Internal Use (Sirius Financial Solutions Plc) -->
<!-- pmnav_map_id = 18 -->
<!DOCTYPE MAP SYSTEM "navigatorxmv2.dtd">
<MAP WMTaskCode="OPENCLM" WMTaskDescription="Complete OpenClaim" ImageURL="http://www.siriusgroup.co.uk" TransactionType="C_CO" ProcessMode="0" 

AutoClose="False" NavigatorDriven="True" Title="NavigatorXM" RoadmapName="Open Claim" Core="1" Version="200" ElementID="E1">
	<STEP Description="Find Policy" Component="iSIRFindInsurance.Interface_Renamed" Type="FF" CancelAction="AP" OKAction="F1" OKSteps="1" CancelSteps="0" 

ComponentAction="2" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E2"/>
	<STEP Description="Claim Details" Component="iOpenClaim.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" 

ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E3">
		<KEY Name="claim_mode" Value="1" ElementID="E4"/>
	</STEP>
	<STEP Description="Check Unpaid Status" Component="iCLMCheckUnpaidPremium.Interface_Renamed" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" 

CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" 

ElementID="E19"/>
	<STEP Description="Information Check list" Component="iCLMInfoChklst.Interface_Renamed" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" 

CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" 

ElementID="E5">
		<KEY Name="DeleteWorkTableFlag" Value="1" ElementID="E6"/>
	</STEP>
	<STEP Description="Risk Details" Component="iCLMRiskDetails.Interface_Renamed" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" 

ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E7"/>
	<STEP Description="Coinsurance Recoveries" Component="iCLMCoinsuranceRecoveries.Interface_Renamed" Type="DF" CancelAction="AP" OKAction="F1" 

OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" 

ElementID="E8"/>
	<STEP Description="Reinsurance Recoveries" Component="iCLMReinsurance.Interface_Renamed" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" 

CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" 

ElementID="E9"/>
	<STEP Description="Salvage Recovery" Component="iCLMRecovery.Interface_Renamed" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" 

ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E10">
		<KEY Name="recovery_is_salvage" Value="1" ElementID="E17"/>
	</STEP>
	<STEP Description="Third Party Recovery" Component="iCLMRecovery.Interface_Renamed" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" 

CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" 

ElementID="E11">
		<KEY Name="recovery_is_salvage" Value="0" ElementID="E18"/>
	</STEP>
	<STEP Description="Update Claim Details" Component="iCLMChangeClaimStatus.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" 

CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" 

ElementID="E12"/>
	<STEP Description="Generate Claim Notification Documents?" Component="iPMDecision.Interface_Renamed" Type="QF" CancelAction="FX" OKAction="F1" 

OKSteps="0" CancelSteps="1" ComponentAction="0" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" 

ElementID="E13">
		<KEY Name="decision_title" Value="Documentation" ElementID="E14"/>
		<KEY Name="decision_text" Value="Generate Claim Notification?" ElementID="E15"/>
	</STEP>
	<STEP Description="Produce Claim Notification Documents" Component="iCLMGetClaimDocuments.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" 

OKSteps="0" CancelSteps="0" ComponentAction="0" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" 

ElementID="E16"/>
	<STEP Description="Claim Payments Process" Component="iCLMPaymentProcess.NavigatorV3" Type="DF" CancelAction="AP" OKAction="CP" OKSteps="0" 

CancelSteps="0" ComponentAction="0" ServerSide="False" CreateWMTask="False" ResumeStep="" Core="1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" 

ElementID="E20"/>
</MAP>

=== RevathiNimmy/pureinsurance/Navigator XM Roadmaps/PMBNBID21.XML
<?xml version="1.0"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by Rob Courtney (Sirius Financial Systems) -->
<!-- pmnav_map_id = 253 -->
<!DOCTYPE MAP SYSTEM "navigatorxmV2.dtd">
<MAP AutoClose="False" ImageURL="http://www.siriusgroup.co.uk" NavigatorDriven="True" ProcessMode="4" RoadmapName="New Business - Stage 1" Title="NavigatorXM" TransactionType="RN D" WMTaskCode="PMBNB" WMTaskDescription="Complete New Business" Core="1" ElementID="E1" Version="200">
	<STEP CancelAction="AP" CancelSteps="0" Component="iPMBFindParty.Interface_Renamed" ComponentAction="1" CreateWMTask="1" Description="Find Client" OKAction="F1" OKSteps="0" OKNewRoadmap="" CancelNewRoadmap="" ResumeStep="-1" ServerSide="0" Submap="" Type="FF" ElementID="E2" Core="1"/>
	<STEP CancelAction="AP" CancelSteps="0" Component="iPMBRoadmap.NavigatorV3" ComponentAction="1" CreateWMTask="1" Description="Add Client Text Files" OKAction="F1" OKSteps="0" OKNewRoadmap="" CancelNewRoadmap="" ResumeStep="-1" ServerSide="0" Submap="" Type="DF" ElementID="E3" Core="1">
		<KEY Name="nav_step" Value="ACLTEXT" ElementID="E4"/>
	</STEP>
	<STEP CancelAction="AP" CancelSteps="0" Component="iPMBPolicy.Interface_Renamed" ComponentAction="1" CreateWMTask="1" Description="Add a policy" OKAction="F1" OKSteps="0" OKNewRoadmap="" CancelNewRoadmap="" ResumeStep="-1" ServerSide="0" Submap="" Type="DF" ElementID="E15" Core="1"/>
	<STEP CancelAction="AP" CancelSteps="0" Component="iPMBRisk.Interface_Renamed" ComponentAction="2" CreateWMTask="1" Description="Add risk info" OKAction="F1" OKSteps="0" OKNewRoadmap="" CancelNewRoadmap="" ResumeStep="-1" ServerSide="0" Submap="" Type="DF" ElementID="E16" Core="1"/>
	<STEP CancelAction="AP" CancelSteps="0" Component="iPMBRoadmap.NavigatorV3" ComponentAction="1" CreateWMTask="1" Description="Add policy text files" OKAction="F1" OKSteps="0" OKNewRoadmap="" CancelNewRoadmap="" ResumeStep="-1" ServerSide="0" Submap="" Type="DF" ElementID="E17" Core="1">
		<KEY Name="nav_step" Value="APLTEXT" ElementID="E18"/>
	</STEP>
	<STEP CancelAction="AP" CancelSteps="0" Component="iPMBTransactionsWrapper.NavigatorV3" ComponentAction="1" CreateWMTask="1" Description="Raise debit" OKAction="F1" OKSteps="0" OKNewRoadmap="" CancelNewRoadmap="" ResumeStep="-1" ServerSide="0" Submap="" Type="DF" ElementID="E29" Core="1"/>
	<STEP CancelAction="AP" CancelSteps="0" Component="iPMBRoadmap.NavigatorV3" ComponentAction="1" CreateWMTask="1" Description="Receive Payment Roadmap" OKAction="F1" OKSteps="0" OKNewRoadmap="" CancelNewRoadmap="" ResumeStep="-1" ServerSide="0" Submap="" Type="DF" ElementID="E40" Core="1">
		<KEY Name="nav_step" Value="PAYMENT" ElementID="E41"/>
	</STEP>
	<STEP Description="Cash List" Component="iACTCashList.NavigatorV3" Type="DF" CancelAction="FX" OKAction="F1" OKSteps="0" CancelSteps="2" ComponentAction="1" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" CheckSystemOption="66" SystemOptionValue="1" ShowWMTaskInterface="False" ElementID="E40">
		<KEY Name="cash_list_roadmap" Value="DECIDE" ElementID="E41"/>
	</STEP>
	<STEP Description="Cash List Item" Component="iACTCashListItem.Interface_Renamed" Type="DF" CancelAction="FX" OKAction="F1" OKSteps="0" CancelSteps="1" ComponentAction="2" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" CheckSystemOption="66" SystemOptionValue="1" ShowWMTaskInterface="False" ElementID="E42">
		<KEY Name="allow_allocate_button" Value="-1" ElementID="E43"/>
	</STEP>
	<STEP Description="Letter to client" Component="iPMBRoadmap.NavigatorV3" Type="DF" CancelAction="AP" OKAction="F1" OKSteps="0" CancelSteps="0" ComponentAction="1" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E42">
		<KEY Name="nav_step" Value="DOCUMENT" ElementID="E43"/>
		<KEY Name="roadmap_document" Value="NBDOC1" ElementID="E44"/>
	</STEP>
	<STEP Description="Await documents from insurer" Component="iPMBRoadmap.NavigatorV3" Type="DF" CancelAction="AP" OKAction="CP" OKSteps="0" CancelSteps="0" ComponentAction="2" ServerSide="False" CreateWMTask="True" Core="1" ResumeStep="-1" Submap="" OKNewRoadmap="" CancelNewRoadmap="" ElementID="E45">
		<KEY Name="nav_step" Value="WMTASK" ElementID="E46"/>
		<KEY Name="wm_task" Value="PMBNB5" ElementID="E47"/>
		<KEY Name="wm_description" Value="[NB] Awaiting documents from Insurer" ElementID="E48"/>
		<KEY Name="wm_step" Value="WMNB4" ElementID="E49"/>
	</STEP>
</MAP>
